### PR TITLE
Motor Control Board Full Review

### PR DESCRIPTION
**Pull request by jhuang2006**

### CODE REVIEW

**Review by ManavToor — DISMISSED** [review]
Off to a good start, did a very quick overview, here are some issues and comments:

1. Please annotate your schematic
2. 10A fuse for LiPo seems really high, what's the expected current draw?
3. Please source diodes and add their part numbers as their value
4. When making CAN connector footprint, make sure the pinout matches all other boards on RocketCAN, also perhaps consider adding a fuse to the 12V input as well as making the diode a shottky.
5. Please comment what servo and encoder you have sourced near the connectors so I can verify their connections
6. Your crystal has no datasheet, how did you calculate load capacitor values? Also why the switch to 16MHz, all our PIC's run at 12MHz.
7. Why'd you change the decoupling caps on the MCP2562? We use just one 10uF on other boards.
8. Just make the cap DNM.
image
9. Connect the 10k MCLR pull-up on the Root sheet so we're more consistent with other boards' schematics
10. What are the MCU's communicating with each other? Is it a simple on/off or will it require a communication protocol with more pins?
11. You have 2 CAN transcievers but only one connection to the bus. Verify with Joe or Jason but this MAY cause problems if both MCU's are trying to send messages at the same time.
12. Can you please comment design parameters for current sensing, so other people can follow through the datasheet and check your work. Also any reason for not using INA180, this is what we use for all other boards, it's nice to stay consistent.
13. No harm in adding a fuse to the LDO if you can
14. Please source a MOSFET and add it's part number as it's value

**Comment by jhuang2006** [comment]
@Joe-Joe-Joe-Joe @JasonBrave 
From Manav: You have 2 CAN transcievers but only one connection to the bus. Verify with Joe or Jason but this MAY cause problems if both MCU's are trying to send messages at the same time.
Can you guys confirm if this will be an issue of not?

**Comment by Joe-Joe-Joe-Joe** [comment]
...
I don't want to sound glib but that's literally how CAN works.
All the CANH/CANL lines are one net. Whether they are tied together on the PCB or via the harness is electrically irrelevant

If that doesn't make sense google "CAN arbitration"

**Comment by jhuang2006** [comment]
@ManavToor Thanks for the review!
1. lmk if there's anything else that should be annotated
2. Servo can draw ~5A max at stall
3. Selected a diode from the waterloo rocketry parts list that works. Waiting on Jason to announce a standardized charging diode. Removed the flyback diode for the servo as it's difficult to source one with such a high current rating (was probably unnecessary anways)
4. i think i did it right? fuse added
5. done
6. Switched to 12MHz. Load caps calculated using 18pF load capacitance from the datasheet and an assumed 5pF stray capacitance
7. I believe the datasheet recommends 2 100nF decoupling caps, but I changed it to 10uF
8. thanks! this makes a ton of sense
9. done
10. simple on/off so digital high/low.
11. addressed
12. Didn't use INA180 for two primary reasons: it takes more pins than I2C when the board needs to be respun to suppport 4 servos which will result in more pins required than the PIC18f26k83 has, and I like having the overcurrent alert functionality which I currently plan to configure so that it triggers an interrupt on the MCU when the servos are close to stalling to center them. 
13. done
14. done

**Review by Redstone-ray — CHANGES_REQUESTED** [review]
1. Pull down
image
2. 10**uF**
image
3, Per Ben's request, ctrl + D
image
4. Can I get a power LED?
5. Where are my wires (DNC?)
image
6. As a good practise, pull your unused pins to ground  (add a resistor so you don't turn it into an output accidentally)
7.

**Review by StarlightDescender — DISMISSED** [review]
1. We now have a standard diode, PMEG2010ER
2. Fuse on the CAN connector is way too large - charging is 1A CC among at *least* 3 LiPos. 1A max is fine I think.
3. You should have a specific part for the harwin datamate, and you might need 2 power and GND pins depending on the max current rating of the connector, and the maximum motor draw currrent.
4. No GND labels on any of the GND symbols? this doesn't really matter but its a little bit strange IMO
5. Might be a skill issue but I can't figure out what the purpose of the SSR is?
6. Why use an LDO for 12V->5V rather than a buck converter? seems like 5V has enough purposes for a buck to be worth it.
7. Probably want voltage feedback on the battery - IE a large voltage divider with the output going to an ADC on the MCU
8. No current reading on 12V/5V?
9. Take a look at other boards (charging board, for example) for the standard oscillator we use.
10. Maybe a 3rd LED on FS to show which is commanding the servo? (ie turns on when FS is active)

Re: @Redstone-ray I think 10uF is fine rather than 10mF? This is what we have done historically on the team. Looking at the datasheet of the MCP2562  though, it suggests 100nF on both the Vdd and Vio. At the same time though, you have the right capacitor value on the main MCU??

**Comment by Redstone-ray** [comment]
Sorry yes @AshTheEngiqueer 10uF

**Comment by Armaan-Sengupta** [comment]
1. Looks like the kikad footprints submodule you have is just local, its not a valid remote commit hash, if you have actually relevant changes there then pls merge it into an actual branch. Because of this I can not see the foot prints of many components. (cc. @JasonBrave can I merge [7e7ed58 ](https://github.com/waterloo-rocketry/kicad-footprints/tree/7e7ed58b0c2f65ee47442cebcdaf7ac9d957cf29) into main?). 
2. Assign your reference designators
3. Your LEDs will draw around 5mA, make sure you source 5mA LEDs not 20mA which I think is more common (I think the ones we have lying around in the bay are 5mA??)
4. Two separate grounds for clarity: 
image
5. A lot of stuff is using 5V, have you checked its all less than 0.5A (how much your LDO can support). If it is anywhere close to half an amp, then you are dropping around 3W on that LDO in which case I agree with Ash, a buck should be used.
6. For your current sense shunt use a 13 milli ohm resistor, that will still let you sense up to 6.3A of current (assuming you are using ADCRANGE = 0, thus allowing up to 81.92mV across the resistor), our servo will not draw more than 4.5A at stall 
image
7. Splitting this up makes it confusing, put that resistor into the MCU sub-pages else tracking the connections on that pin is needlessly jumping around
image
8. Failsafe override should be high to close the mosphet (enable pwm from main MCU) and low to disable, so the opposite of what it is now, you will need to source a nromally open version of the optocoupler relay you chose (also thats a bit a extra a mosphet woulda done fine since you are not concerned about back propigation of voltage but its fine if you want to leave it). Also would be nice if there was an LED for this.
image
9. So say the override kicks in, then what happens, the optocoupler cuts off the connection between the MCU's PWM and the servo, so essentially we send it no control signal, have we validated what this does on our servos, because it does not nessicarily mean they will go back to the center, keep in mind center is 1500uS pulse width (666Hz) so I am not entirely sure what no signal does. You are in person so this is easy to check, just set the servo to some non center position then while it is there unplug the signal line.
10. We have two encoders, so add another encoder line
11. The encoder datasheet (I am assuming you are going with WAL200_e?) is very limited, but it looks like it implements the voltage divider already so you dont need to add your own voltage divider, directly tie it to an analog input pin on the PIC 18, check the datasheet for the PIC 18 to see how much current it draws when doing an analogue input read, it should be high impedance so very less, but this encoder says you can only draw 1uA which is super low so double check.
12. Mark as DNP, it will only be added presumably pre flight? I assume we can still program with this cap there but its just not best practise?
image

**Review by Armaan-Sengupta — DISMISSED** [review]
1. Looks like the kikad footprints submodule you have is just local, its not a valid remote commit hash, if you have actually relevant changes there then pls merge it into an actual branch. Because of this I can not see the foot prints of many components. (cc. @JasonBrave can I merge [7e7ed58 ](https://github.com/waterloo-rocketry/kicad-footprints/tree/7e7ed58b0c2f65ee47442cebcdaf7ac9d957cf29) into main?). 
2. Assign your reference designators
3. Your LEDs will draw around 5mA, make sure you source 5mA LEDs not 20mA which I think is more common (I think the ones we have lying around in the bay are 5mA??)
4. Two separate grounds for clarity: 
image
5. A lot of stuff is using 5V, have you checked its all less than 0.5A (how much your LDO can support). If it is anywhere close to half an amp, then you are dropping around 3W on that LDO in which case I agree with Ash, a buck should be used.
6. For your current sense shunt use a 13 milli ohm resistor, that will still let you sense up to 6.3A of current (assuming you are using ADCRANGE = 0, thus allowing up to 81.92mV across the resistor), our servo will not draw more than 4.5A at stall 
image
7. Splitting this up makes it confusing, put that resistor into the MCU sub-pages else tracking the connections on that pin is needlessly jumping around
image
8. Failsafe override should be high to close the mosphet (enable pwm from main MCU) and low to disable, so the opposite of what it is now, you will need to source a nromally open version of the optocoupler relay you chose (also thats a bit a extra a mosphet woulda done fine since you are not concerned about back propigation of voltage but its fine if you want to leave it). Also would be nice if there was an LED for this.
image
9. So say the override kicks in, then what happens, the optocoupler cuts off the connection between the MCU's PWM and the servo, so essentially we send it no control signal, have we validated what this does on our servos, because it does not nessicarily mean they will go back to the center, keep in mind center is 1500uS pulse width (666Hz) so I am not entirely sure what no signal does. You are in person so this is easy to check, just set the servo to some non center position then while it is there unplug the signal line.
10. We have two encoders, so add another encoder line
11. The encoder datasheet (I am assuming you are going with WAL200_e?) is very limited, but it looks like it implements the voltage divider already so you dont need to add your own voltage divider, directly tie it to an analog input pin on the PIC 18, check the datasheet for the PIC 18 to see how much current it draws when doing an analogue input read, it should be high impedance so very less, but this encoder says you can only draw 1uA which is super low so double check.
12. Mark as DNP, it will only be added presumably pre flight? I assume we can still program with this cap there but its just not best practise?
image

**Comment by jhuang2006** [comment]
@AshTheEngiqueer 
4. I can bring the GND labels back if that's preferred. Some people think the GND label is redundant (which it is) and makes the schematic messy.
5. SSR is so the FS MCU can shut down the PWM lines from the primary MCU and write its own pwm. I'm not sure how this would behave with a regular mosfet since the gate is not electrically isolated so SSR to be safe unless someone is confident that a mosfet will be fine.
6. 5V line will draw ~100mA max, assuming all LEDs are on. I don't want to use a buck to avoid having to do more filtering for the potentiometer.
7. INA232 can also report voltage
8. Is there a good reason to also measure/log current on the 5V line and 12V line?
9. Standard osc is kinda big and we're trying to keep the board small for integration sake. Richard said we'll buy a stencil and use reflow soldering for this
10. Uhh trying to avoid adding more LEDs. 4 + 1 for PWR is alr a lot. Any reason we can't just blink an LED faster or both simultaneously to indicate additional things?

**Comment by jhuang2006** [comment]
@Armaan-Sengupta 
3. What LEDs are proc board using? last years schematic shows it using a 330 ohm resistor on 3.3V
5. ~100mA assuming all LEDs on. LDO is spec'ed to 500mA.
6. makes sense
8. Oh. I was going to do the opposite (high = override so mosfet is open). Probably should put a pull down resistor to make it normally low if this is the case. Logic being i don't want the FS losing power to override MCU. I suppose i could do the same thing by using a pull up resistor which would make low = override but this is not consistent with what I did for the pwr mosfet.
9. Planning on cutting the MCU pwm line and writing 1500us to the servo from the FS itself so we should only have like 100ms without signal
11. going with GL60 since we want the IP63 rating. Sorry will update the design doc. I'm planning on using the 4.096V internal fixed voltage reference on the PIC18 since its very stable so I need to voltage divide the 0-5V range to 0-4.096V, unless you think I should use the 5V Vin as my analog ref.
12. yep. Is there a difference between DNM and DNP?

**Comment by StarlightDescender** [comment]
@rexblade21 
4. Fair enough, I don't think its a big deal? Just what I'm used to lol
5. Yup that makes sense. Maybe there's a way to do it with two mosfets? ex. MOTOR_EN control from charging board but SSR is also fine. Only reason you might prefer mosfets is a smaller effective footprint (you lose most of the space on the other side of the SSR because through-hole.
6. Very curious how you determined less than 100mA with all LEDs on given there are two microcontrollers - that seems sus to me.
7. Fair enough, WRRTDC:I
8. Oops you're right, charging board trauma
9. Fair enough
10. I don't see a power LED?

new stuff:
1. A bit confusing that the input and output are on the same side - what I'd do is I'd swap the location of pins 2 and 3 on the symbol so you can have 12V on the left, 5V on the right
2. LiPo connector shouldn't be an XT30 - while yes that is what directly connects to the LiPo, I don't think the LiPo wire should be assumed to be long enough (if there is CAD to prove otherwise then sure). For example, last year we crimped XT30 -> ring terminal wires of the correct lengths, and used a screw terminal.

**Comment by Redstone-ray** [comment]
@AshTheEngiqueer There's a lot of conflicting comments on power LEDs lmao, Armaan thinks there's already too many and we should instead just alterate the flashing sequence, and I want a power LED asw, I think either case its acceptable, cause we already have 4 and having extra could indeed lead to confusion.

I think for our integration the lipo will most likely sit right next to the motor controller board... there's no place for them anywhere else anyways, but yeah screw terminal is prob a good idea

**Comment by StarlightDescender** [comment]
@Redstone-ray My only argument for 1 LED -> 1 message is that you can tell very quickly what the board is doing. What are you imagining the power LED is communicating, out of curiosity?

**Comment by Armaan-Sengupta** [comment]
@JasonBrave I meant like actually mark it in the properties as DNP (DNM is the same terminology). using a stable vref makes sense. I would think that low being ovveride makes more sense as a deadman switch type thing, so if it does loose power then the intended action would be to override it. None of this is critical so if its routed already as is then dw.

**Comment by Redstone-ray** [comment]
1. what's the point of this
image

2. Right angle bend
image

3. Woba 22 Errors on DRC ok I'll stop right here and wait for you to fix them
image

**Comment by Redstone-ray** [comment]
1. I fixed most DRC warnings but these you should address
image

2. Why is your CPC1117N footprint different from recommended pattern?
image
image

3. Might shove that lock file into .gitignore

**Comment by Redstone-ray** [comment]
> @Redstone-ray My only argument for 1 LED -> 1 message is that you can tell very quickly what the board is doing. What are you imagining the power LED is communicating, out of curiosity?

To check the connection with the servo (servo is powered vs unpowered)

**Comment by StarlightDescender** [comment]
@Redstone-ray Yup, I think we're in agreement? Like what I'd suggest is 1 white 1 blue per pic (white is heartbeat, blue shows pwm signal from that pic) and then 1 red (motor powered or not)

**Comment by FinnBreu** [comment]
### Design rules of the manufacturer?
1. I'm assuming (the nearest traces seem exactly 250um away soo...) you checked the design rules, especially copper/copper spacing, solder mask damns, via diameters. Just wanted to make sure

2. Can you move the via in the middle of the Servo+ net out of there?
(And that sharp 90 on the left just bugs me even tho it does not matter)
grafik

3. What temperture rise do you expect on these 3 vias (right) on the ground path? They don't look that large. Would add two more 
grafik

4. Clean up some traces maybe 
grafik

5. Maybe move the oscis further away. The angles look sharp and you have the room. Not necessary though
grafik

6. Some polygon islands can be removed if you feel like it 
grafik

Looks good from my brief inspection of this. Board size is quite small so I understand the routing decisions, even if it looks a bit messy (your words)

**Comment by Joe-Joe-Joe-Joe** [comment]
1. I think it would be cleaner to put your MCU programming connectors inside the sub-sheets. Current top level is a bit cramped
2. What is happening with LiPO harnessing? I see you have picked a very nice harwin connector for the LiPo, is this going to become a new standard? We normally use deans<->ring terminal, I am seeing discussion of XT30s as well? very curious about this
3. Encoders. What are the seemingly orphaned net labels `ENC1/2_IN` and what are these connectors? I expect I missed some technical discussion on the matter but every time you introduce a new connector, especially Harwins, you introduce more complexity everywhere. Its another part we have to stock (beg Harwin for) and keep track of, including at comp. For two 3-wire, low-current devices I feel like it makes a lot of sense to use a single standard 6 pin gecko
4. Why do you have a 1A fuse for a 0.5A max LDO on a line that supposedly shouldn't draw more than 0.25A? Also another orphaned net label
image
5. I see the 6 pin datamate footprint has gotten a makeover. Kinda tangential, but I [made the Gecko mounting screw holes plated](https://github.com/waterloo-rocketry/canhw/pull/63#pullrequestreview-1630119401) when I originally did it. Further research suggests this maybe questionable for ungrounded mounting holes and liable to do more harm than good? Whatever the case, we should be consistent with which one we use and change the other to match (and also put a keepout on the actual connector area like the Gecko)
https://electronics.stackexchange.com/questions/115965/should-mounting-holes-be-plated
https://electronics.stackexchange.com/questions/36837/why-are-vias-placed-this-way-on-a-pcb/36845#36845
6. This number is not nice and round. Please make the spacing nice and round
image
7. MCLR silkscreen callout? I know its tight but damn I hate pulling up the kicad for this
image
8. Please gitignore the backups folder
9. As this is the final review, please generate the fabrication files as well

**Comment by Redstone-ray** [comment]
Let's change the name of the board, just so to avoid any confusions @rexblade21

**Comment by Redstone-ray** [comment]
@Joe-Joe-Joe-Joe This year we will keep using the deans & ring terminal since I can't confirm sponsorship for them to keep in line with team standard, but I think it's worth a discussion to potentially move to something that's more secure, and less vulnerable to vibrations.

@rexblade21 to make that change tn

**Comment by jhuang2006** [comment]
@FinnBreu 
1. Yep complies with JLC minimums and team minimums
2. Fixed
3. Good point! Fixed
4. lol i tried
5. i'm not going to move them this time but good to know for future
6. removed

**Comment by jhuang2006** [comment]
@Joe-Joe-Joe-Joe 
1. ok
2. As richard said, I switched it over to the ring connector, however this did make the board a fair bit larger. Probably should've requested sponsorship from harwin earlier but oh well too late now
3. Good to know. One connector for two connectors seems kinda cringe especially when they are diametrically opposite but it makes sense given the harwin connectors we have. There's no space for a gecko and we don't have time to reroute the board so we'll just use the current connectors. They only cost ~$7 on digikey and we only need one of them now (probably only one encoder) so it's not the end of the world if harwin won't give them to us.
4. fixed
5. made the datamate PTH but in other boards they aren't lol. This is the datamate that was used last year, but horizontal as opposed to vertical to match the orientation of every other connector on the board. It seems like the team has used these before? See: https://waterloorocketry.slack.com/archives/C07MX0QDS/p1721100477056439 will confirm that we have them.
6. Fixed
7. good point
8. i think i did it?
9. ok

**Review by Redstone-ray — APPROVED** [review]
LGTM, Great work.

**Review by StarlightDescender — APPROVED** [review]
1. No isolated ground pour around your oscillators? 
image
It _probably_ doesn't matter too much? but bad practice and could potentially cause minor issues

2. This might be unnecessary (someone to fact check me would be great) but I'm fairly sure CANH/CANL traces should be matching length or very close to? at minimum its good practice

3. Daisychaining here is easily fixable 
image
image
image
image
and so on. Again, at this point it's not a huge deal, but something to note for next time.

4. Some of the spacing looks a little bit tight, but you know your soldering skills the best. From the 3D model it looks like you have a decent amount of space? If this wasn't so urgent I'd say try to make better use of it, but it's not a huge issue I don't think.

Other than that, LGTM. I'll approve this so if these aren't issues in your opinion, you can merge and order.

**Comment by Joe-Joe-Joe-Joe** [comment]
Length matching CAN traces is a meme its not necessary

**Review by Joe-Joe-Joe-Joe — APPROVED** [review]
1. J4 Part number no longer correct
image
2. I meant put them in MCU.kicad_sch and FS.kicad_sch
image

**Comment by FinnBreu** [comment]
Las thing:
That via in Servo+ annoys me. Approved other than that
grafik

**Review by FinnBreu — APPROVED** [review]

**Comment by Redstone-ray** [comment]
All look good, merging

**Pull request merged**
